# Generated by Django 5.0.1 on 2024-01-06 19:16

import imageAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clothImage",
                    models.ImageField(
                        blank=True, null=True, upload_to=imageAPI.models.cloth_upload_to
                    ),
                ),
                (
                    "personImage",
                    models.ImageField(
                        blank=True, null=True, upload_to=imageAPI.models.person_upload_to
                    ),
                ),
                (
                    "clothPersonImage",
                    models.ImageField(
                        blank=True, null=True, upload_to=imageAPI.models.cloth_person_upload_to
                    ),
                ),
                ("descriptin", models.CharField(max_length=100)),
            ],
        ),
    ]
