# Generated by Django 5.0.1 on 2024-01-06 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("imageAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="descriptin",
            new_name="description",
        ),
    ]
