# Generated by Django 5.0.1 on 2024-01-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageAPI", "0002_rename_descriptin_images_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="description",
            field=models.CharField(default="no description", max_length=100),
        ),
    ]
